config/routes.rb
Rails.application.routes.draw do
  scope module: 'web' do
    resources :users
    resources :tasks do
      member do
        post :start
        get  :start, as: :easy_start
        post :finish
        get  :finish, as: :easy_finish
        get  :reactivate, as: :easy_reactivate
        post :assign_to
      end
    end

    root to: 'welcome#index'
  end

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  resources :sessions, only: [:create]
end

app/models/task.rb
class Task < ActiveRecord::Base
  # Associations
  belongs_to :user

  # Validators
  validates :name, presence: true
  validates :user_id, presence: true

  # States
  state_machine :state, initial: :new do
    before_transition any => :started do |task, transition|
      task.started_at = DateTime.now
    end
    before_transition started: :finished do |task, transition|
      task.finished_at = DateTime.now
    end

    event :start do
      transition :new => :started
    end

    event :finish do
      transition started: :finished
    end

    event :reactivate do
      transition finished: :started
    end
  end

  # Scopes
  scope :initiated, ->{where(state: 'new')}
  scope :started, ->{where(state: 'started')}
  scope :finished, ->{where(state: 'finished')}

  # Attachments
  mount_uploader :attachment, AttachmentUploader
end

app/controllers/web/tasks_controller.rb
class Web::TasksController < Web::ApplicationController
  before_action :authenticate_user
  before_action :protect_restricted_form_params, only: [:create, :update]
  before_action :load_resource, only: [:edit, :update, :show, :destroy, :start, :finish, :reactivate, :assign_to]
  before_action :on_resource_not_found, only: [:edit, :update, :show, :destroy]

  def index
    tasks = Task.order(:id)
    tasks = tasks.where(user_id: current_user.id) if current_user.user?

    @tasks = tasks.all
  end

  def new
    @task = Task.new user_id: user_id_for_task
  end

  def create
    @task = Task.new(resource_params)

    if @task.save
      redirect_to tasks_path, notice: t(:resource_created, scope: 'task.messages')
    else
      flash.now.alert = t(:resource_data_has_errors, scope: 'task.messages')
      render :new
    end
  end

  def edit
  end

  def update

    if @task.update_attributes(resource_params)
      redirect_to tasks_path, notice: t(:resource_updated, scope: 'task.messages')
    else
      flash.now.alert = t(:resource_data_has_errors, scope: 'task.messages')
      render :edit
    end
  end

  def show
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: t(:resource_removed, scope: 'task.messages')
  end

  def start
    if request.post?
      render(json: {status: "ERROR", reason: t(:resource_not_found, scope: 'task.messages')}) and return if @task.blank?
      if @task.start
        render json: {status: "OK", started_at: @task.started_at}
      else
        render json: {status: "ERROR", reason: @task.errors.full_messages.try(:first)}
      end
    else
      if @task.start
        redirect_to tasks_path, notice: t(:resource_updated, scope: 'task.messages')
      else
        redirect_to tasks_path, alert: t(:resource_data_has_errors, scope: 'task.messages')
      end
    end
  end

  def finish
    if request.post?
      render(json: {status: "ERROR", reason: t(:resource_not_found, scope: 'task.messages')}) and return if @task.blank?
      if @task.finish
        render json: {status: "OK", finished_at: @task.finished_at}
      else
        render json: {status: "ERROR", reason: @task.errors.full_messages.try(:first)}
      end
    else
      if @task.finish
        redirect_to tasks_path, notice: t(:resource_updated, scope: 'task.messages')
      else
        redirect_to tasks_path, alert: t(:resource_data_has_errors, scope: 'task.messages')
      end
    end
  end

  def reactivate
    if @task.reactivate
      redirect_to tasks_path, notice: t(:resource_updated, scope: 'task.messages')
    else
      redirect_to tasks_path, alert: t(:resource_data_has_errors, scope: 'task.messages')
    end
  end

  def assign_to
    render(json: {status: 'ERROR', reason: t(:permission_denied)}) and return unless current_user.admin?
    render(json: {status: "ERROR", reason: t(:resource_not_found, scope: 'task.messages')}) and return if @task.blank?
    render(json: {status: "ERROR", reason: t(:resource_not_found, scope: 'user.messages')}) and return unless User.exists?(params[:user_id])
    @task.user_id = params[:user_id]
    if @task.save
      render json: {status: "OK"}
    else
      render json: {status: "ERROR", reason: @task.errors.full_messages.join(";")}
    end
  end

  private
    def resource_params
      params.require(:task).permit(:name, :description, :user_id, :attachment, :attachment_cache, :remote_attachment_url)
    end

    def user_id_for_task(user_id_from_param = params[:user_id])
      if current_user.admin?
        user_id_from_param || current_user.id
      else
        current_user.id
      end
    end

    def protect_restricted_form_params
      params[:task].merge!("user_id" => user_id_for_task(params[:task][:user_id])) if params[:task][:user_id].present?
    end

    def load_resource
      @task =
        if current_user.admin?
          Task.where(id: params[:id]).first
        else
          current_user.tasks.where(id: params[:id]).first
        end
    end

    def on_resource_not_found
      redirect_to tasks_path, alert: t(:resource_not_found, scope: 'task.messages') unless @task.present?
    end
end

app/helpers/web/tasks_helper.rb
module Web::TasksHelper
  def show_attachment
    if @task.attachment.try(:content_type).try(:match, /image/i)
      image_tag(@task.attachment_url)
    else
      link_to(@task.attachment.model[:attachment], @task.attachment_url, target: '_blank')
    end
  rescue
    ""
  end
end

app/views/web/tasks/_form.html.slim
= simple_form_for @task, class: "form-horizontal", role: "form" do |f|
  = f.input :name
  = f.input :description
  = show_attachment if @task.attachment.file.present?
  = f.file_field :attachment
  = f.input :attachment_cache, as: :hidden
  - if current_user.admin?
    = f.input :user_id, collection: User.all, label_method: :email, value_method: :id, include_blank: false
  - else
    = f.input :user_id, as: :hidden

  .btn-group
    = f.button :submit, class: "btn btn-primary"
    = link_to "Cancel", :back, class: "btn btn-warning", data: {confirm: 'Are you sure to leave this page?'}

app/views/web/tasks/_row.html.slim
tr.item-row
  td= task.name
  td title="#{task.description if task.description && task.description.length > 30}" = task.description.try(:truncate, 30, separator: '...')
  - if current_user.admin?
    td= task.user.email
  td
    = task.state
  td
    .btn-group
      - if task.new?
        = render '/shared/action_button', glyphicon_class: "glyphicon-play", title: "start", action_path: easy_start_task_path(task)
      - if task.started?
        = render '/shared/action_button', glyphicon_class: "glyphicon-stop", title: "finish", action_path: easy_finish_task_path(task)
      - if task.finished?
        = render '/shared/action_button', glyphicon_class: "glyphicon-repeat", title: "reactivate", action_path: easy_reactivate_task_path(task)
  td= task.created_at.try(:strftime, '%d/%m/%Y %H:%M')
  td
    .btn-group
      = render '/shared/action_button', glyphicon_class: "glyphicon-edit", title: "edit", action_path: edit_task_path(task)
      = render '/shared/action_button', glyphicon_class: "glyphicon-search", title: "view", action_path: task_path(task)
      = render '/shared/action_button', glyphicon_class: "glyphicon-trash", title: "delete", action_path: "/tasks/#{task.id}", method: "delete", confirm: "You trying delete task! Are you sure?"

app/views/web/tasks/edit.html.slim
.row
  .col-md-3
    .h3
      b Edit Task:
.row
  .col-md-12
    = render 'form', task: @task

app/views/web/tasks/index.html.slim
.row
  .col-md-3
    .h3
      b Task list:
  .col-md-1.col-md-offset-8
    == link_to "Create New", new_task_path, class: "btn btn-success"
.row
  .col-md-12
    table.table.table-striped.table-hover
      thead
        tr
          td Name
          td Description
          - if current_user.admin?
            td User
          td State
          td
          td Create
          td Actions
      tbody
        = render partial: "row", collection: @tasks, as: :task

app/views/web/tasks/new.html.slim
.row
  .col-md-3
    .h3
      b Create Task:
.row
  .col-md-12
    = render 'form', task: @task

app/views/web/tasks/show.html.slim
.row
  .col-md-3
    .h3
      b Task details:
.row
  .col-md-12
    .row
      dl.dl-horizontal
        dt Name
        dd= @task.name

        dt Description
        dd= @task.description

        - unless @task.attachment.file.nil?
          dt Attachment
          dd= show_attachment


        - if current_user.admin?
          dt User assigned
          dd= @task.user.email

        dt State
        dd= @task.state

        dt Created at
        dd= @task.created_at.try(:strftime, '%d/%m/%Y %H:%M')

        - if @task.started?
          dt Started at
          dd= @task.started_at.try(:strftime, '%d/%m/%Y %H:%M')

        - if @task.finished?
          dt Finished at
          dd= @task.finished_at.try(:strftime, '%d/%m/%Y %H:%M')

.row
  .col-md-4
    .btn-group
      = link_to 'Edit', edit_task_path(@task), class: "btn btn-success"
      = link_to 'To List', tasks_path, class: "btn btn-default"