config/routes.rb
Rails.application.routes.draw do
  scope module: 'web' do
    resources :users
    resources :tasks do
      member do
        post :start
        get  :start, as: :easy_start
        post :finish
        get  :finish, as: :easy_finish
        get  :reactivate, as: :easy_reactivate
        post :assign_to
      end
    end

    root to: 'welcome#index'
  end

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  resources :sessions, only: [:create]
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password, :password_confirmation
  ROLES = %w(ADMIN USER)

  # Associations
  has_many :tasks, dependent: :destroy

  # Validators
  validates :email, uniqueness: true
  validates :email, presence: true
  validates :email, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}

  validates :encrypted_password, presence: true

  validates :password, presence: true, if: Proc.new {|_user| _user.new_record? || _user.password_confirmation.present?}
  validates :password_confirmation, presence: true, if: Proc.new {|_user| _user.new_record? || _user.password.present?}

  validates :password, confirmation: true

  validates :role, inclusion: {in: ROLES}


  # Callbacks
  before_validation :encrypt_password, if: Proc.new {|_user| _user.password.present? || _user.password_confirmation.present?}

  def self.authenticate(email, password)
    user = User.find_by_email(email.downcase)
    if user && BCrypt::Password.new(user.encrypted_password) == password
      user
    else
      nil
    end
  end

  def user?
    role == "USER"
  end

  def admin?
    role == "ADMIN"
  end

  def encrypt_password
    self.encrypted_password = BCrypt::Password.create(@password).to_s if @password.present? && @password == @password_confirmation
  end
end

app/controllers/web/users_controller.rb
class Web::UsersController < Web::ApplicationController
  before_action :authenticate_user
  before_action :check_admin_permissions, only: [:index, :new, :create, :destroy]
  before_action :check_admin_or_self_permissions, only: [:edit, :update, :show]
  before_action :load_resource, only: [:edit, :update, :show, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(resource_params)

    if @user.save
      redirect_to users_path, notice: t(:resource_created, scope: 'user.messages')
    else
      flash.now.alert = t(:resource_data_has_errors, scope: 'user.messages')
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(resource_params)
      redirect_to resolve_redirect_path, notice: t(:resource_updated, scope: 'user.messages')
    else
      flash.now.alert = t(:resource_data_has_errors, scope: 'user.messages')
      render :edit
    end
  end

  def show
  end

  def destroy
    redirect_to users_path, alert: t(:admin_selfdestruction_error, scope: 'user.messages') and return if current_user.admin? && current_user.id == params[:id].to_i
    @user.destroy
    redirect_to resolve_redirect_path, notice: t(:resource_removed, scope: 'user.messages')
  end

  private
    def check_admin_permissions
      redirect_to user_path(current_user), alert: t(:permission_denied) unless current_user.admin?
    end

    def check_admin_or_self_permissions
      redirect_to user_path(current_user), alert: t(:permission_denied) unless current_user.admin? || current_user.id == params[:id].try(:to_i)
    end

    def resource_params
      params.require(:user).permit(:email, :password, :password_confirmation, :role)
    end

    def load_resource
      @user = User.where(id: params[:id]).first

      redirect_to resolve_redirect_path, alert: t(:resource_not_found, scope: 'user.messages') if @user.blank?
    end

    def resolve_redirect_path
      current_user.admin? ? users_path : user_path(current_user)
    end
end

app/views/web/users/_form.html.slim
= simple_form_for @user, class: "form-horizontal", role: "form" do |f|
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  - if current_user.admin?
    = f.input :role, collection: User::ROLES, include_blank: false

  .btn-group
    = f.button :submit, class: "btn btn-primary"
    = link_to "Cancel", :back, class: "btn btn-warning", data: {confirm: 'Are you sure to leave this page?'}

app/views/web/users/_row.html.slim
tr.item-row
  td= user.email
  td= user.role
  td= user.created_at.try(:strftime, '%d/%m/%Y %H:%M')
  td= user.updated_at.try(:strftime, '%d/%m/%Y %H:%M')
  td
    .btn-group
      = render '/shared/action_button', glyphicon_class: "glyphicon-edit", title: "edit", action_path: edit_user_path(user)
      = render '/shared/action_button', glyphicon_class: "glyphicon-search", title: "view", action_path: user_path(user)
      - unless current_user.id == user.id
        = render '/shared/action_button', glyphicon_class: "glyphicon-trash", title: "delete", action_path: "/user/#{user.id}", method: "delete", confirm: "You trying delete account! Are you sure?"

app/views/web/users/edit.html.slim
.row
  .col-md-3
    .h3
      b Edit User:
.row
  .col-md-12
    = render 'form', task: @user

app/views/web/users/index.html.slim
.row
  .col-md-3
    .h3
      b User list:
  .col-md-1.col-md-offset-8
    == link_to "Create New", new_user_path, class: "btn btn-success"
.row
  .col-md-12
    table.table.table-striped.table-hover
      thead
        tr
          td Email
          td Role
          td Created at
          td Updated at
          td Actions
      tbody
        = render partial: "row", collection: @users, as: :user

app/views/web/users/new.html.slim
.row
  .col-md-3
    .h3
      b Create User:
.row
  .col-md-12
    = render 'form', task: @user

app/views/web/users/show.html.slim
.row
  .col-md-3
    .h3
      b User details:
.row
  .col-md-12
    .row
      dl.dl-horizontal
        dt Email
        dd= @user.email

        - if current_user.admin?
          dt Role
          dd= @user.role
.row
  .col-md-4
    .btn-group
      = link_to 'Edit', edit_user_path(@user), class: "btn btn-success"
      - if current_user.admin?
        = link_to 'To List', users_path, class: 'btn btn-default'