config/routes.rb
Rails.application.routes.draw do
  scope module: 'web' do
    resources :users
    resources :tasks do
      member do
        post :start
        get  :start, as: :easy_start
        post :finish
        get  :finish, as: :easy_finish
        get  :reactivate, as: :easy_reactivate
        post :assign_to
      end
    end

    root to: 'welcome#index'
  end

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  resources :sessions, only: [:create]
end

app/views/shared/_action_button.html.slim
- glyphicon_class ||= ""
- title           ||= ""
- action_path     ||= ""
- method          ||= "get"
- confirm         ||= nil

= link_to action_path, class: "btn btn-default", title: title, method: method, data: {confirm: confirm} do
  span.glyphicon class=glyphicon_class

app/views/shared/_nav_bar.html.slim
nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      a.navbar-brand href='/' Task Manager
    ul.nav.navbar-nav
      li class="#{'active' if controller.controller_name == 'tasks'}"
        = link_to 'Tasks', tasks_path
      - if current_user.admin?
        li class="#{'active' if controller.controller_name == 'users'}"
          = link_to 'Users', users_path
    ul.nav.navbar-nav.navbar-right
      li
        = link_to user_path(current_user) do
          = content_tag :span, nil, class: "glyphicon glyphicon-user"
          | Profile
      li
        = link_to log_out_path do
          = content_tag :span, nil, class: "glyphicon glyphicon-log-out"
          | Logout